// Generated by https://quicktype.io

export interface SiteResponse {
  total: number;
  sites: Site[];
}

export interface Site {
  id: string;
  corporation: Author;
  author: Author;
  name: string;
  abbreviated_name: null;
  address: Address;
  coordinate: Coordinate;
  unit: Unit;
  work_period: WorkPeriod;
  work_type: WorkType;
  photo_url: null;
  note: null;
  detailed_preference: { [key: string]: null };
  archive: boolean;
  status: string;
  transfer_active: boolean;
  link_group_active: boolean;
  link_group_id: null;
}

export interface Address {
  country: string;
  zip_code: null;
  state: string;
  city: string;
  address_1: null;
  address_2: null;
}

export interface Author {
  id: string;
  name: string;
}

export interface Coordinate {
  latitude: string;
  longitude: string;
  time_zone: string;
}

export interface Unit {
  distance: string;
  area: string;
  volume: string;
  currency: string;
  weight: string;
}

export interface WorkPeriod {
  planned_start_date: string;
  planned_end_date: string;
  start_date: string;
  end_date: string;
}

export interface WorkType {
  i_con: string;
  type: string;
  name: null;
}
