version: '3.9'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "cl-viewer-api-swagger-ui"
    ports:
      - "9010:8080"
    volumes:
      - ./openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml
